<?php
require_once ('connect.php');
require('pdf/fpdf.php');

class PDF extends FPDF{
    function Header()
    {
        parent::Header(); // TODO: Change the autogenerated stub
        $this->AddFont('courier','','angsa.php');
        $this->SetFont('courier','',12);
        $this->SetLeftMargin(10);
        $this->Cell(0,5,iconv("UTF-8","TIS-620",'สวัสดีฉันเบื่อ '),0,1);
        $this->Cell(0,5,iconv("UTF-8","TIS-620",'สวัสดีฉันเบื่อ'),0,1);
        $this->Cell(0,5,iconv("UTF-8","TIS-620",'สวัสดีฉันเบื่อ '),0,1);
        $this->Ln(10);
        $this->Line(5,25,200,25);
        $this->SetLeftMargin(5);
    }
    function Footer()
    {
        parent::Footer(); // TODO: Change the autogenerated stub
        $this->SetLineWidth(0,5);
        $this->AddFont('courier','','angsa.php');
        $this->SetFont('courier','',10);
        $this->SetY(-12);
        $this->Cell(0,5,iconv("UTF-8","TIS-620",'สรนนวรตตสสต'),0,1,"L");
        $this->Cell(0,5,iconv("UTF-8","TIS-620",'ฉะะะีึรคราาาาีตนนต' .date('d').'/'.date('m').'/'.(date('Y')+543).''.date('H:i:s')),0,0,"R");
    }
}function thaidate1($str){
    if($str=="0000-000-000") {return "าทดำาดทา";}
    $y = substr($str,0,4) +543;
    $m = substr($str,5,2) +0;
    $d = substr($str,8,2);
    $month = array("ม.ค.","ก.พ.","มี.ค.","เม.ย.","พ.ค.","มิ.ย.","ก.ค.","ส.ค.","ก.ย.","ต.ค.","พ.ย.","ธ.ค.");
    return $d ." ".$month[$m-1]." ".$y;
}
function thaidate($str){
    if($str=="0000-000-000") {return "าทดำาดทา";}
    $m = substr($str,5,2) +0;
    $month = array("มกราคม","กุมภาพันธ์","มีนาคม","เมษายน","พฤษภาคม","มิถุนายน","กรกฎาคม","สิงหาคม","กันยายน","ตุลาคม","พฤศจิกายน","ธันวาคม");
    return $month[$m-1];
}
$date = date("Y-m-d");
function getNumDaynews($d1,$d2){
    $dArr1 =preg_split("/-/",$d1);
    list($year1,$month1,$day1) = $dArr1;
    $Day1 = mktime(0,0,0,$month1,$day1,$year1);
    $dArr2 =preg_split("/-/",$d2);
    list($year2,$month2,$day2) = $dArr2;
    $Day2 = mktime(0,0,0,$month2,$day2,$year2);
    return round(abs($Day1 - $Day2) / 86400)+1;
}

$pdf =new PDF('P','mm','A4');
$pdf->AddPage();
$pdf->Ln(5);
$pdf->AddFont('courier','','angsa.php');
$pdf->SetFont('courier','',14);
$pdf->Cell(175,4,iconv("UTF-8","TIS-620",'สวัสดีฉันเบื่อ ฉันกลัวทำไม่ทัน'),0,1,'C');
$pdf->Ln(2);
$pdf->Cell(10,7,iconv("UTF-8","TIS-620",'1'),1,0,'C');
$pdf->Cell(15,7,iconv("UTF-8","TIS-620",'รหัส'),1,0,'C');
$pdf->Cell(45,7,iconv("UTF-8","TIS-620",'พรพรเ่ืเ่กานไนสไน'),1,0,'C');
$pdf->Cell(55,7,iconv("UTF-8","TIS-620",'บะนยาปกยยบกใใำสสไไ'),1,0,'C');
$pdf->Cell(18,7,iconv("UTF-8","TIS-620",'ำนพมะเา้สกมทืหรกนก'),1,0,'C');
$pdf->Cell(50,7,iconv("UTF-8","TIS-620",'สอออออออกกกกกกกกำำำำำำำำ'),1,0,'C');
$pdf->Cell(15,7,iconv("UTF-8","TIS-620",'หน้ัวสว้ัมวัั้สาวยดยดยดด'),1,0,'C');
$pdf->Ln();

$pdf->Output("report.pdf","I")
?>
